### ISSUE TITLE
Create filter to only analyze given commands

### ISSUE THREAD

**Issue by beatrizbonafe** [laimaretto/logChecker#27]
Useful for cases where [taskAutom](https://github.com/laimaretto/taskAutom) executes multiple commands, including those that should not be compared or should not have information in excel file.

**Comment by laimaretto** [comment]
@beatrizbonafe : I think this can be solved by doing the following:

1) in the folder of the textFSM templates only leave the teamplates that we are interested in;
2) disable using the generic template.

In this way, only a new CLI parameter is needed: useGen as yer/no. By default this will be yes, because we want to use the generic template. But in cases where we need to parse a certain amount of commands, we would do se according to the above bullets.

**Comment by beatrizbonafe** [comment]
Solved in [Version 4.5.7](https://github.com/laimaretto/logChecker/commit/a4ca933e63727aa4671c8b70388a036dba788196)
